In [163]:
import pandas as pd
import numpy as np
from IPython import get_ipython
from nbformat import read
from IPython.core.interactiveshell import InteractiveShell
from method_of_moments import mom
from code1 import G
from code1 import g
from scipy.special import polygamma
from scipy.special import digamma
import numpy as np
import math
from numpy.linalg import inv

In [29]:
excel_file = 'Glass_data.xlsx'
glass = pd.read_excel(excel_file)

In [30]:
glass.head()

Id        RI  Sodium  Magnesium  Aluminum  Silicon  Potassium  Calcium  \
0    1  1.52101   13.64       4.49      1.10    71.78       0.06     8.75   
1    2  1.51761   13.89       3.60      1.36    72.73       0.48     7.83   
2    3  1.51618   13.53       3.55      1.54    72.99       0.39     7.78   
3    4  1.51766   13.21       3.69      1.29    72.61       0.57     8.22   
4    5  1.51742   13.27       3.62      1.24    73.08       0.55     8.07   

   Barium  Iron  Type of glass  
0     0.0   0.0              1  
1     0.0   0.0              1  
2     0.0   0.0              1  
3     0.0   0.0              1  
4     0.0   0.0              1

In [31]:
Y1 = pd.read_excel(excel_file,parse_cols = [2], encoding="utf-8-sig",sep='\s*,\s*')
Y1.head()


Sodium
0   13.64
1   13.89
2   13.53
3   13.21
4   13.27

In [36]:
print(glass.columns.tolist())

['Id ', 'RI', 'Sodium', 'Magnesium', 'Aluminum', 'Silicon', 'Potassium', 'Calcium', 'Barium', 'Iron', 'Type of glass']


In [38]:
Y1 = glass['Magnesium']

In [39]:
Y2 = glass['Aluminum']
Y3 = glass['Silicon']
Y4 = glass['Potassium']
Y5 = glass['Calcium']
Y6 = glass['Barium']
Y7 = glass['Iron']

X = glass['RI']

In [60]:
Y1.head()

0    4.49
1    3.60
2    3.55
3    3.69
4    3.62
Name: Magnesium, dtype: float64

In [65]:

print (Y1[1])

3.6


In [76]:
Y7 = Y7.values

In [83]:
Y = [[Y1],[Y2]]

In [94]:
len(Y)

2

In [90]:
print (Y1[0])

4.49


In [95]:
len(Y1)

214

In [96]:
y1 = Y1/20

In [97]:
print (y1)

[ 0.2245  0.18    0.1775  0.1845  0.181   0.1805  0.18    0.1805  0.179
  0.18    0.173   0.183   0.1715  0.178   0.1795  0.177   0.1835  0.1925
  0.1865  0.177   0.1775  0.1875  0.181   0.1785  0.175   0.177   0.174
  0.174   0.176   0.1745  0.178   0.175   0.174   0.1735  0.177   0.1725
  0.1765  0.174   0.191   0.191   0.175   0.171   0.1695  0.192   0.1715
  0.174   0.1685  0.185   0.1885  0.1675  0.186   0.1665  0.1435  0.142
  0.1405  0.1355  0.1735  0.174   0.187   0.183   0.181   0.179   0.193
  0.1905  0.187   0.1795  0.1825  0.1825  0.179   0.179   0.1835  0.1935
  0.1795  0.1785  0.178   0.179   0.1805  0.179   0.176   0.176   0.176
  0.1725  0.1775  0.176   0.1545  0.179   0.1745  0.1745  0.175   0.174
  0.187   0.172   0.1705  0.167   0.1665  0.1715  0.181   0.1625  0.144
  0.148   0.1425  0.136   0.138   0.1575  0.145   0.      0.      0.      0.
  0.      0.      0.      0.      0.1915  0.1985  0.1945  0.195   0.184
  0.182   0.1785  0.188   0.177   0.177   0.174   0.184

In [100]:
SumY = Y1+Y2+Y3+Y4+Y5+Y6+Y7

In [101]:
y1 = Y1/SumY

In [102]:
y2 = Y2/SumY
y3 = Y3/SumY
y4 = Y4/SumY
y5 = Y5/SumY
y6 = Y6/SumY
y7 = Y7/SumY



In [103]:
print (y2)

[ 0.01276398  0.01581395  0.01785507  0.01493401  0.01432532  0.01858438
  0.01316701  0.01210933  0.01595063  0.0156268   0.01788581  0.01458094
  0.01607532  0.01457592  0.01501089  0.01414118  0.01329513  0.01042155
  0.01372412  0.01942305  0.01711857  0.00340816  0.01482929  0.01549053
  0.01330557  0.01391925  0.01629116  0.01531552  0.0163972   0.01476015
  0.01487755  0.01310044  0.01411198  0.01578045  0.01537579  0.01398359
  0.01533814  0.01549765  0.00548169  0.00548169  0.01286469  0.01378518
  0.01534733  0.00834976  0.01363897  0.01563767  0.01358977  0.0082635
  0.00911188  0.01427577  0.0059103   0.01474315  0.01376041  0.01478231
  0.01487889  0.01473275  0.0128958   0.01487032  0.01352288  0.01374293
  0.01286658  0.01533101  0.01018401  0.00910896  0.01040342  0.01299907
  0.01000575  0.00999426  0.01035792  0.00945681  0.02048987  0.01471952
  0.0175297   0.01814819  0.01773581  0.0173843   0.01785921  0.01778291
  0.014518    0.02185415  0.02437902  0.01652797  0.

In [106]:
#[[a],[b]] = mom(Y)
[[a1],[c1]]= mom(y1)

In [107]:
print (a1,c1)

3.34100543076 104.404565129


In [129]:
y = np.array([y1,y2,y3,y4,y5,y6,y7])
#yy = np.concatenate((y1,y2))

In [130]:
print (y[0][0],y[1][0])


0.0521002552796 0.0127639823625


In [131]:
print (y1[0],y2[0])

0.0521002552796 0.0127639823625


In [136]:
vect_mom = np.vectorize(mom,otypes=[np.float],cache=False)

In [143]:
[[a1],[c1]]= mom(y[1])

In [146]:
for i in range(0, 3):
    print ("Were on time ",i)

Were on time  0
Were on time  1
Were on time  2


In [215]:
a = [0]*7
c = [0] * 7
for i in range(0, 6):
    [[a[i]],[c[i]]]= mom(y[i])
    print(a[i],c[i])

3.53813338869 109.847052098
8.1009764969 476.395741073
837.660743903 159.211036262
0.620547966993 105.062126495
37.2343776855 322.334128321
0.269386124883 93.7997297599


In [216]:
#teta = [[a],[b]]
#X = [0.1,0.2,0.3,0.4]
#teta_new = teta - np.matmul(inv(G(a,b)),g(a,b,X))
#print (teta_new)


In [258]:
def newton(teta,X):
    while(1):
     for i in range(0,6):
         print('Divya')
         delta = np.matmul(inv(G(teta[0][i],teta[1][i])),g(teta[0][i],teta[1][i],X[i]))
         teta_new = teta - delta
         dif = teta_new - teta
         print(delta)
     if (dif.all()<0.001) : break;
     teta = teta_new     
    return teta_new;


In [259]:
for i in (0,6,1):
         print('Divya')

Divya
Divya
Divya


In [272]:
teta = [a,c]

In [269]:
a = [0.1]*7
c = [0.5] * 7

In [273]:
print (teta[0][0],teta[1][0])

0.1 0.5


In [274]:
print (teta)

[[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1], [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]]


In [275]:

teta_new = newton(teta,y)

Divya
[[-0.0682736 ]
 [-0.49230771]]
Divya
[[-0.06695542]
 [-0.50013795]]
Divya
[[-0.05419905]
 [ 0.93738331]]
Divya
[[-0.05134785]
 [-0.46487607]]
Divya
[[-0.08540192]
 [-0.48048169]]
Divya
[[-0.0400627 ]
 [-0.43561323]]
Divya
[[-0.08859518]
 [-0.98228469]]
Divya
[[-0.0865373 ]
 [-1.01791438]]
Divya
[[ 0.00545212]
 [ 4.83221047]]
Divya
[[-0.05607665]
 [-0.91589666]]
Divya
[[-0.11961747]
 [-0.88741579]]
Divya
[[-0.03387251]
 [-0.8267133 ]]
Divya
[[-0.11193558]
 [-1.95711538]]
Divya
[[-0.11053323]
 [-2.12108357]]
Divya
[[  0.25276471]
 [ 22.02367876]]
Divya
[[-0.06435418]
 [-1.88648493]]
Divya
[[-0.15093798]
 [-1.35548665]]
Divya
[[-0.03009369]
 [-1.65281252]]
Divya
[[-0.13976225]
 [-3.64408386]]
Divya
[[-0.14272467]
 [-4.37171842]]
Divya
[[  0.96349529]
 [ 95.00862497]]
Divya
[[-0.08182744]
 [-3.9873741 ]]
Divya
[[-0.16870313]
 [-0.51282323]]
Divya
[[-0.03497065]
 [-3.44459301]]
Divya
[[-0.16860947]
 [-5.38383544]]
Divya
[[-0.18529125]
 [-8.47215364]]
Divya
[[   2.88866121]
 [ 395.1833

Divya
[[ -1.45708874e-13]
 [ -8.98532634e-11]]
Divya
[[    7.99809661]
 [ 5708.63586699]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789805]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801245]]
Divya
[[  5.15286909e-13]
 [  3.19338651e-10]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.81178419]]
Divya
[[    672.81829872]
 [ 419173.12789725]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801241]]
Divya
[[ -1.42858508e-13]
 [ -8.88660452e-11]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789748]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801242]]
Divya
[[ -1.43808630e-13]
 [ -8.91951180e-11]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789771]]
Divy

Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789768]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801243]]
Divya
[[  1.86214200e-13]
 [  1.15236303e-10]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789738]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801241]]
Divya
[[  1.85264079e-13]
 [  1.14907230e-10]]
Divya
[[    7.99809661]
 [ 5708.63586697]]
Divya
[[    2.62317835]
 [ 2328.81178419]]
Divya
[[    672.81829872]
 [ 419173.12789695]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801239]]
Divya
[[ -4.74781582e-13]
 [ -2.93955611e-10]]
Divya
[[    7.99809661]
 [ 5708.63586699]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789788]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divy

Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789738]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801241]]
Divya
[[ -1.44758752e-13]
 [ -8.95241907e-11]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789774]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801243]]
Divya
[[  1.85264079e-13]
 [  1.14907230e-10]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789743]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801242]]
Divya
[[ -1.43808630e-13]
 [ -8.91951180e-11]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789767]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divy

[[  1.84313957e-13]
 [  1.14578157e-10]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789752]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801242]]
Divya
[[ -1.42858508e-13]
 [ -8.88660452e-11]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789771]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801243]]
Divya
[[  1.86214200e-13]
 [  1.15236303e-10]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789741]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801241]]
Divya
[[ -1.44758752e-13]
 [ -8.95241907e-11]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789768]]
Divya
[[  

Divya
[[    672.81829872]
 [ 419173.12789765]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801243]]
Divya
[[ -1.45708874e-13]
 [ -8.98532634e-11]]
Divya
[[    7.99809661]
 [ 5708.63586699]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789788]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801244]]
Divya
[[  1.86214200e-13]
 [  1.15236303e-10]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789745]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801242]]
Divya
[[ -1.44758752e-13]
 [ -8.95241907e-11]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789781]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801244]]
Divya
[[  1.86214200e-13]
 [  1.15236303e-10]

Divya
[[    672.81829872]
 [ 419173.12789793]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801244]]
Divya
[[  1.83363835e-13]
 [  1.14249085e-10]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789762]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801243]]
Divya
[[  1.86214200e-13]
 [  1.15236303e-10]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.81178419]]
Divya
[[    672.81829872]
 [ 419173.12789732]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801241]]
Divya
[[  1.84313957e-13]
 [  1.14578157e-10]]
Divya
[[    7.99809661]
 [ 5708.63586697]]
Divya
[[    2.62317835]
 [ 2328.81178419]]
Divya
[[    672.81829872]
 [ 419173.12789697]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801239]]
Divya
[[ -4.71931217e-13]
 [ -2.92968393e-10]

 [ 419173.12789729]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801241]]
Divya
[[ -1.42858508e-13]
 [ -8.88660452e-11]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789752]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801242]]
Divya
[[ -1.43808630e-13]
 [ -8.91951180e-11]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789775]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801243]]
Divya
[[  1.86214200e-13]
 [  1.15236303e-10]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789741]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801241]]
Divya
[[ -1.44758752e-13]
 [ -8.95241907e-11]]
Divya
[[    7.99809661]


Divya
[[    672.81829872]
 [ 419173.12789788]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801244]]
Divya
[[  1.88114444e-13]
 [  1.15894448e-10]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789749]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801242]]
Divya
[[ -1.44758752e-13]
 [ -8.95241907e-11]]
Divya
[[    7.99809661]
 [ 5708.63586699]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789785]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801244]]
Divya
[[  5.15286909e-13]
 [  3.19338651e-10]]
Divya
[[    7.99809661]
 [ 5708.63586697]]
Divya
[[    2.62317835]
 [ 2328.81178419]]
Divya
[[    672.81829872]
 [ 419173.12789697]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801239]]
Divya
[[ -1.44758752e-13]
 [ -8.95241907e-11]

Divya
[[    7.99809661]
 [ 5708.63586697]]
Divya
[[    2.62317835]
 [ 2328.81178419]]
Divya
[[    672.81829872]
 [ 419173.12789704]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801239]]
Divya
[[ -4.73831460e-13]
 [ -2.93626539e-10]]
Divya
[[    7.99809661]
 [ 5708.63586699]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.1278979 ]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801244]]
Divya
[[ -1.44758752e-13]
 [ -8.95241907e-11]]
Divya
[[    7.99809661]
 [ 5708.63586699]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789809]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801245]]
Divya
[[  5.15286909e-13]
 [  3.19338651e-10]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.81178419]]
Divya
[[    672.81829872]
 [ 419173.12789729]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divy

[[    672.81829872]
 [ 419173.12789752]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801242]]
Divya
[[ -1.44758752e-13]
 [ -8.95241907e-11]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789779]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801244]]
Divya
[[  1.84313957e-13]
 [  1.14578157e-10]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.81178419]]
Divya
[[    672.81829872]
 [ 419173.1278974 ]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801241]]
Divya
[[ -4.72881338e-13]
 [ -2.93297466e-10]]
Divya
[[    7.99809661]
 [ 5708.63586699]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789821]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801246]]
Divya
[[  5.15286909e-13]
 [  3.19338651e-10]]
Divy

 [ 2328.81178419]]
Divya
[[    672.81829872]
 [ 419173.12789723]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672]
 [ 22913.4980124]]
Divya
[[ -4.73831460e-13]
 [ -2.93626539e-10]]
Divya
[[    7.99809661]
 [ 5708.63586699]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789796]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801245]]
Divya
[[  1.86214200e-13]
 [  1.15236303e-10]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789774]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801243]]
Divya
[[  1.84313957e-13]
 [  1.14578157e-10]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789743]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801242]]
Divya
[[  1.86214200e-13]
 [

Divya
[[    34.9257672 ]
 [ 22913.49801241]]
Divya
[[ -1.43808630e-13]
 [ -8.91951180e-11]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789755]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801242]]
Divya
[[ -1.42858508e-13]
 [ -8.88660452e-11]]
Divya
[[    7.99809661]
 [ 5708.63586699]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789782]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801244]]
Divya
[[  1.86214200e-13]
 [  1.15236303e-10]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789752]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801242]]
Divya
[[ -1.44758752e-13]
 [ -8.95241907e-11]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya


 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.81178419]]
Divya
[[    672.81829872]
 [ 419173.12789736]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801241]]
Divya
[[ -1.43808630e-13]
 [ -8.91951180e-11]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789772]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801243]]
Divya
[[  1.85264079e-13]
 [  1.14907230e-10]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.81178419]]
Divya
[[    672.81829872]
 [ 419173.12789737]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801241]]
Divya
[[ -1.44758752e-13]
 [ -8.95241907e-11]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.1278976 ]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 

[[    672.81829872]
 [ 419173.12789753]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801242]]
Divya
[[ -1.43808630e-13]
 [ -8.91951180e-11]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789781]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801244]]
Divya
[[  1.85264079e-13]
 [  1.14907230e-10]]
Divya
[[    7.99809661]
 [ 5708.63586698]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.1278975 ]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801242]]
Divya
[[ -4.73831460e-13]
 [ -2.93626539e-10]]
Divya
[[    7.99809661]
 [ 5708.63586699]]
Divya
[[    2.62317835]
 [ 2328.8117842 ]]
Divya
[[    672.81829872]
 [ 419173.12789827]]
Divya
[[  5.75496581e-02]
 [  3.27876454e+02]]
Divya
[[    34.9257672 ]
 [ 22913.49801246]]
Divya
[[  1.85264079e-13]
 [  1.14907230e-10]]
Divy

KeyboardInterrupt: 

In [180]:
y[y == 0] = 0.001

In [276]:
for i in (0,6):
         teta_new = teta - np.matmul(inv(G(teta[0][i],teta[1][i])),g(teta[0][i],teta[1][i],y))


In [264]:
print (teta_new)

[[ -980035.70256779  -980031.13972469  -979201.57995728  -980038.62015322
   -980002.0063235   -980038.97131506  -980039.24070118]
 [-1055718.0319293  -1055351.48324033 -1055668.66794514 -1055722.8168549
  -1055505.54485308 -1055734.07925164 -1055827.8789814 ]]
